# Generated by Django 5.0.13 on 2025-04-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
